#!/bin/bash
set -euo pipefail

exec > >(tee /var/log/user-data.log | logger -t user-data -s 2>/dev/console) 2>&1

PROJECT_NAME="${project_name}"
DOCKERHUB_USER="${dockerhub_user}"
IMAGE_TAG="${image_tag}"
DEPLOY_DIR="/opt/do2526-deploy"
COMPOSE_FILE="$DEPLOY_DIR/docker-compose.deploy.yml"
COMPOSE_FALLBACK_VERSION="v2.33.1"

log() {
  echo "[$(date -Is)] $*"
}

retry() {
  local attempts="$1"
  local sleep_seconds="$2"
  shift 2

  local attempt=1
  until "$@"; do
    if [ "$attempt" -ge "$attempts" ]; then
      log "Command failed after $attempt attempts: $*"
      return 1
    fi

    log "Attempt $attempt/$attempts failed. Retrying in $sleep_seconds seconds: $*"
    attempt=$((attempt + 1))
    sleep "$sleep_seconds"
  done
}

download() {
  local url="$1"
  local out="$2"
  retry 5 10 wget -q -O "$out" "$url"
}

install_compose_plugin_if_needed() {
  # If compose already works, do nothing
  if docker compose version >/dev/null 2>&1; then
    return 0
  fi

  # AL2023 suele tener este nombre (docker-compose-plugin NO siempre existe)
  retry 3 5 dnf install -y docker-cli-plugin-compose && return 0

  # Fallback: descargar binario de compose como CLI plugin
  local arch
  case "$(uname -m)" in
    x86_64) arch="x86_64" ;;
    aarch64|arm64) arch="aarch64" ;;
    *)
      log "Unsupported architecture for Docker Compose fallback: $(uname -m)"
      return 1
      ;;
  esac

  mkdir -p /usr/local/lib/docker/cli-plugins
  download "https://github.com/docker/compose/releases/download/$COMPOSE_FALLBACK_VERSION/docker-compose-linux-$arch" \
           /usr/local/lib/docker/cli-plugins/docker-compose
  chmod +x /usr/local/lib/docker/cli-plugins/docker-compose

  docker compose version
}

prepare_ssm_agent() {
  if systemctl list-unit-files amazon-ssm-agent.service >/dev/null 2>&1; then
    systemctl enable --now amazon-ssm-agent
    return 0
  fi

  retry 3 5 dnf install -y amazon-ssm-agent
  systemctl enable --now amazon-ssm-agent
}

write_compose_file() {
  mkdir -p "$DEPLOY_DIR"

  cat > "$COMPOSE_FILE" <<EOF
# Generated by cloud-init user_data. Manual changes will be overwritten.
services:
  nginx:
    image: $DOCKERHUB_USER/do2526-nginx-gateway:$IMAGE_TAG
    container_name: nginx-gateway
    ports:
      - "80:80"
    depends_on:
      search-api:
        condition: service_started
        restart: true
      songs-api:
        condition: service_started
        restart: true
      movies-api:
        condition: service_started
        restart: true
      football-api:
        condition: service_started
        restart: true
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 15s
    networks:
      - group-network
    restart: unless-stopped

  songs-api:
    image: danvelcam621/songs-api:latest
    container_name: songs-api
    environment:
      - MONGO_URI=mongodb://songs-mongo:27017
      - NODE_ENV=production
    depends_on:
      songs-mongo:
        condition: service_healthy
    networks:
      - group-network
    restart: unless-stopped

  songs-mongo:
    image: mongo
    container_name: songs-mongo
    volumes:
      - songs-mongo-data:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - group-network
    restart: unless-stopped

  movies-api:
    image: migencmar/moviesapi:latest
    container_name: movies-api
    environment:
      - MONGO_URL=mongodb://movies-mongo:27017
      - NODE_ENV=production
    depends_on:
      movies-mongo:
        condition: service_healthy
    networks:
      - group-network
    restart: unless-stopped

  movies-mongo:
    image: mongo
    container_name: movies-mongo
    volumes:
      - movies-mongo-data:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - group-network
    restart: unless-stopped

  football-api:
    image: jorgeflorentino8/footballteamapi:latest
    container_name: football-api
    environment:
      - MONGO_URL=mongodb://football-mongo:27017
      - NODE_ENV=production
    depends_on:
      football-mongo:
        condition: service_healthy
    networks:
      - group-network
    restart: unless-stopped

  football-mongo:
    image: mongo
    container_name: football-mongo
    volumes:
      - football-mongo-data:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - group-network
    restart: unless-stopped

  search-api:
    image: $DOCKERHUB_USER/do2526-search-api:$IMAGE_TAG
    container_name: search-api
    environment:
      - SONGS_API_URL=http://songs-api:8080
      - MOVIES_API_URL=http://movies-api:8080
      - FOOTBALL_API_URL=http://football-api:8080
      - NODE_ENV=production
    depends_on:
      - songs-api
      - movies-api
      - football-api
    networks:
      - group-network
    restart: unless-stopped

networks:
  group-network:
    driver: bridge

volumes:
  songs-mongo-data:
  movies-mongo-data:
  football-mongo-data:
EOF
}

start_compose_stack() {
  cd "$DEPLOY_DIR"
  retry 5 15 docker compose -p "$PROJECT_NAME" -f "$COMPOSE_FILE" pull
  retry 5 15 docker compose -p "$PROJECT_NAME" -f "$COMPOSE_FILE" up -d --remove-orphans
}

verify_gateway() {
  local health_output
  health_output="$(retry 12 5 wget --timeout=3 -q -O - http://127.0.0.1/healthz)"

  if [ "$health_output" != "ok" ]; then
    log "Unexpected healthz response: $health_output"
    return 1
  fi

  log "Gateway health check succeeded: $health_output"
}

main() {
  log "Bootstrapping project $PROJECT_NAME"

  retry 3 10 dnf update -y

  # IMPORTANT: avoid installing curl (conflicts with curl-minimal on AL2023).
  # DO NOT install docker-compose-plugin here; it may not exist in AL2023 repos.
  retry 3 10 dnf install -y docker wget

  systemctl enable --now docker
  retry 5 5 docker info >/dev/null

  prepare_ssm_agent
  install_compose_plugin_if_needed
  write_compose_file
  start_compose_stack
  verify_gateway

  log "Bootstrap completed successfully"
}

main
